#!/usr/bin/env bash
# Configures an Ubuntu machine to install and set up Nginx web server

apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

service nginx start
service nginx restart
